export { default as Header } from './Header';
export { default as Footer } from './Footer';
export { default as Hero } from './Hero';
export { default as Featured } from './Featured';
export { default as Grid } from './Grid';
export { default as Categories } from './Categories';
export { default as Banner } from './Banner';
export { default as NewArrivals } from './NewArrivals';
export { default as Blogs } from './Blogs';
